package com.lsf.entity;

// default package
// Generated May 31, 2016 3:23:31 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * StockId generated by hbm2java
 */
@Embeddable
public class StockId implements java.io.Serializable {

	private int permno;
	private String date;

	public StockId() {
	}

	public StockId(int permno, String date) {
		this.permno = permno;
		this.date = date;
	}

	@Column(name = "PERMNO", nullable = false)
	public int getPermno() {
		return this.permno;
	}

	public void setPermno(int permno) {
		this.permno = permno;
	}

	@Column(name = "date", nullable = false)
	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StockId))
			return false;
		StockId castOther = (StockId) other;

		return (this.getPermno() == castOther.getPermno())
				&& ((this.getDate() == castOther.getDate()) || (this.getDate() != null
						&& castOther.getDate() != null && this.getDate()
						.equals(castOther.getDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPermno();
		result = 37 * result
				+ (getDate() == null ? 0 : this.getDate().hashCode());
		return result;
	}

}
