package com.lsf.entity;

// default package
// Generated May 31, 2016 9:31:23 AM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Stock generated by hbm2java
 */
@Entity
@Table(name = "stock", catalog = "karshacep")
public class Stock implements java.io.Serializable {

	private StockId id;
	private Double prc;
	private Double ret;
	private Integer shrout;
	private Integer vol;
	private Double pseudoPrc;
	private Double pseudoPrcn;
	private Integer rawVol;
	private Double turnover;

	public Stock() {
	}

	public Stock(StockId id) {
		this.id = id;
	}

	public Stock(StockId id, Double prc, Double ret, Integer shrout,
			Integer vol, Double pseudoPrc, Double pseudoPrcn, Integer rawVol,
			Double turnover) {
		this.id = id;
		this.prc = prc;
		this.ret = ret;
		this.shrout = shrout;
		this.vol = vol;
		this.pseudoPrc = pseudoPrc;
		this.pseudoPrcn = pseudoPrcn;
		this.rawVol = rawVol;
		this.turnover = turnover;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "permno", column = @Column(name = "PERMNO", nullable = false)),
			@AttributeOverride(name = "date", column = @Column(name = "date", nullable = false)) })
	public StockId getId() {
		return this.id;
	}

	public void setId(StockId id) {
		this.id = id;
	}

	@Column(name = "PRC", precision = 22, scale = 0)
	public Double getPrc() {
		return this.prc;
	}

	public void setPrc(Double prc) {
		this.prc = prc;
	}

	@Column(name = "RET", precision = 22, scale = 0)
	public Double getRet() {
		return this.ret;
	}

	public void setRet(Double ret) {
		this.ret = ret;
	}

	@Column(name = "SHROUT")
	public Integer getShrout() {
		return this.shrout;
	}

	public void setShrout(Integer shrout) {
		this.shrout = shrout;
	}

	@Column(name = "VOL")
	public Integer getVol() {
		return this.vol;
	}

	public void setVol(Integer vol) {
		this.vol = vol;
	}

	@Column(name = "Pseudo-PRC", precision = 22, scale = 0)
	public Double getPseudoPrc() {
		return this.pseudoPrc;
	}

	public void setPseudoPrc(Double pseudoPrc) {
		this.pseudoPrc = pseudoPrc;
	}

	@Column(name = "PseudoPRCn", precision = 22, scale = 0)
	public Double getPseudoPrcn() {
		return this.pseudoPrcn;
	}

	public void setPseudoPrcn(Double pseudoPrcn) {
		this.pseudoPrcn = pseudoPrcn;
	}

	@Column(name = "RawVol")
	public Integer getRawVol() {
		return this.rawVol;
	}

	public void setRawVol(Integer rawVol) {
		this.rawVol = rawVol;
	}

	@Column(name = "Turnover", precision = 22, scale = 0)
	public Double getTurnover() {
		return this.turnover;
	}

	public void setTurnover(Double turnover) {
		this.turnover = turnover;
	}

}
